### PR TITLE
fix odcds test

### PR DESCRIPTION
**Pull request by wanlill**
seems tests are failing for https://github.com/envoyproxy/envoy/pull/20065 : )

### CODE REVIEW

**Comment by krnowak** [comment]
@wanlill: Thanks for looking at it, I appreciate it. The fix for the test looks good, but could you tell me what was the reason behind the changes in BUILD files?

**Comment by wanlill** [comment]
> but could you tell me what was the reason behind the changes in BUILD files?

Hey Krzesimir, I ran the failed test ([//test/integration:odcds_integration_test](https://dev.azure.com/cncf/envoy/_build/results?buildId=102114&view=logs&j=8c169225-0ae8-53bd-947f-07cb81846cb5&t=6b0ace90-28b2-51d9-2951-b1fd35e67dec&l=7287)) locally and the error is that "envoy.filters.http.on_demand" is not registered. IIUC it indicates the [on_demand](https://github.com/wanlill/envoy/tree/kinvolk-odcds/source/extensions/filters/http/on_demand) libarary is not linked and OnDemandFilterFactory is not registered. Not sure whether this is the right way to fix it but it worked in my environment. (I failed to find the output log for the failed run in the azure pipeline though, so I'm not sure whether the error in the presubmit test is exactly the same)

**Comment by krnowak** [comment]
Hm, now I remember getting the same… Maybe something has changed in the way the extensions are loaded.

**Comment by krnowak** [comment]
Alright, I updated the branch with your commit (I needed to add the "Signed-off-by:" to your commit). Let's see.

Thanks again for the fix!

**Pull request closed without merging**
